version: "3.9"

services:
  app:
    build: ./spring
    image: oauth-app
    container_name: oauth-app
    restart: unless-stopped
    environment:
      APP_YANDEX_CLIENT_ID: ${APP_YANDEX_CLIENT_ID}
      APP_YANDEX_CLIENT_SECRET: ${APP_YANDEX_CLIENT_SECRET}
      APP_GOOGLE_CLIENT_ID: ${APP_GOOGLE_CLIENT_ID}
      APP_GOOGLE_CLIENT_SECRET: ${APP_GOOGLE_CLIENT_SECRET}
      APP_FRONT_URL: http://localhost:3000
      APP_MY_URL: http://localhost:8080
    ports:
      - "8080:8080"

  ui:
    build: ./react
    image: oauth-ui
    container_name: oauth-ui
    restart: unless-stopped
    ports:
      - "3000:80"
