version: "3.9"

services:
  app:
    build: ./spring
    container_name: app
    restart: unless-stopped
    environment:
      APP_YANDEX_CLIENT_ID: ${APP_YANDEX_CLIENT_ID}
      APP_YANDEX_CLIENT_SECRET: ${APP_YANDEX_CLIENT_SECRET}
    ports:
      - "8080:8080"

  ui:
    build: ./react
    container_name: ui
    restart: unless-stopped
    ports:
      - "3000:80"
